SYMPTOMS = [
    "fever",
    "fatigue",
    "chills",
    "weakness",
    "loss_of_appetite",
    "headache",
    "dizziness",
    "confusion",
    "fainting",
    "difficulty_concentrating",
    "cough",
    "shortness_of_breath",
    "chest_tightness",
    "wheezing",
    "sore_throat",
    "chest_pain",
    "palpitations",
    "leg_swelling",
    "nausea",
    "vomiting",
    "diarrhea",
    "abdominal_pain",
    "bloating",
    "acid_reflux",
    "muscle_pain",
    "joint_pain",
    "back_pain",
    "runny_nose",
    "nasal_congestion",
    "loss_of_taste_smell",
    "ear_pain",
    "skin_rash",
    "itching",
    "swelling",
    "redness",
    "frequent_urination",
    "painful_urination",
    "burning_sensation",
    "blurred_vision",
    "eye_pain",
    "light_sensitivity",
    "sleep_disturbance",
    "anxiety",
    "low_mood",
]


def encode(symptoms: list[str]) -> list[float]:
    return [1.0 if s in symptoms else 0.0 for s in SYMPTOMS]
